[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_staking = "GGWeSTDbz2WCERf59nTxwSRTFLMg7butvdk9tv4D53sN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
